### ISSUE TITLE
Changing Debug Options crashes visual studio

### ISSUE THREAD

**Issue by mathtone** [nforgeio/RaspberryDebugger#29]
I seem to be able to connect to the Pi and verify the connection but setting the connection in the Raspberry Debug Settings crashes the IDE with the following:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.Diagnostics.Contracts.Covenant.Requires[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Boolean, System.String, System.String)
   at RaspberryDebugger.PackageHelper.GetSolutionProjects(System.Collections.Generic.List`1<EnvDTE.Project>, EnvDTE.Solution, EnvDTE.Project)
   at RaspberryDebugger.PackageHelper.GetSolutionProjects(System.Collections.Generic.List`1<EnvDTE.Project>, EnvDTE.Solution, EnvDTE.Project)
   at RaspberryDebugger.PackageHelper.WriteRaspberryProjects(EnvDTE.Solution, RaspberryDebugger.RaspberryProjects)
   at RaspberryDebugger.SettingsCommand+<Execute>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by mathtone** [comment]
This might have fixed it for me (PackageHelper.cs ln 539):

if(projectItem.SubProject != null)
{
     GetSolutionProjects(solutionProjects,solution,projectItem.SubProject);
}

Are you taking pull requests?

**Comment by jefflill** [comment]
@mathtone: Sure, that would be really nice.  I've been trying to repro this for 20 minutes.

The subproject support is pretty new and this is my first VS extension so I'm still learning.

**Comment by jefflill** [comment]
...or I can just fix it myself since its' only a couple of lines.  Your call if you want to get a GitHub fold star :)

**Comment by jefflill** [comment]
**FIXED** for v1.4

@mathtone: I've just published v1.4 that hopefully fixed this problem (I wasn't actually able to repro it).  It can take some time for extension updates to become available in Visual Studio.  You can download the extension directly from the release if necessary:

https://github.com/nforgeio/RaspberryDebugger/releases/tag/v1.4

Please reopen this if you have any more trouble.
