### ISSUE TITLE
Unable to install - Version not acceptable

### ISSUE THREAD

**Issue by codeputer** [nforgeio/RaspberryDebugger#54]
I'm thinking this is a great extension, and would be happy to update it to for .Net7 and VS 2022.  Not yet having looked at the code base, i'm loggin this result to see if anybody has tried this, or if you know of a blocker and I should not waste my time?

2023-01-19 11:09:28 AM - Microsoft VSIX Installer
2023-01-19 11:09:28 AM - -------------------------------------------
2023-01-19 11:09:28 AM - vsixinstaller.exe version:
2023-01-19 11:09:28 AM - 17.4.2118-17-4P4Inse-ge4c88902
2023-01-19 11:09:28 AM - -------------------------------------------
2023-01-19 11:09:28 AM - Command line parameters:
2023-01-19 11:09:28 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Richard\Downloads\RaspberryDebugger.vsix
2023-01-19 11:09:28 AM - -------------------------------------------
2023-01-19 11:09:28 AM - Microsoft VSIX Installer
2023-01-19 11:09:28 AM - -------------------------------------------
2023-01-19 11:09:28 AM - Initializing Install...
2023-01-19 11:09:28 AM - Extension Details...
2023-01-19 11:09:28 AM - 	Identifier         : Raspberry Debugger.79c7fc56-a78c-4e6b-b73d-f202de491d34
2023-01-19 11:09:28 AM - 	Name               : Raspberry Debugger
2023-01-19 11:09:28 AM - 	Author             : neonFORGE LLC
2023-01-19 11:09:28 AM - 	Version            : 1.6
2023-01-19 11:09:28 AM - 	Description        : The Raspberry Debugger extension provides an easy way to debug your Raspberry .NET Core and .NET 5 applications on a real Raspberry Pi using Visual Studio.
2023-01-19 11:09:28 AM - 	Locale             : en-US
2023-01-19 11:09:28 AM - 	MoreInfoURL        : 
2023-01-19 11:09:28 AM - 	InstalledByMSI     : False
2023-01-19 11:09:28 AM - 	SupportedFrameworkVersionRange : [4.5,)
2023-01-19 11:09:28 AM - 
2023-01-19 11:09:28 AM - 	SignatureState     : Unsigned
2023-01-19 11:09:28 AM - 	Supported Products : 
2023-01-19 11:09:28 AM - 		Microsoft.VisualStudio.Community
2023-01-19 11:09:28 AM - 			Version : [16.0,17.0)
2023-01-19 11:09:28 AM - 			ProductArchitecture : x86
2023-01-19 11:09:28 AM - 		Microsoft.VisualStudio.Pro
2023-01-19 11:09:28 AM - 			Version : [16.0,17.0)
2023-01-19 11:09:28 AM - 			ProductArchitecture : x86
2023-01-19 11:09:28 AM - 		Microsoft.VisualStudio.Pro
2023-01-19 11:09:28 AM - 			Version : [16.0,17.0)
2023-01-19 11:09:28 AM - 			ProductArchitecture : x86
2023-01-19 11:09:28 AM - 
2023-01-19 11:09:28 AM - 	References         : 
2023-01-19 11:09:28 AM - 	Prerequisites      : 
2023-01-19 11:09:28 AM - 		-------------------------------------------------------
2023-01-19 11:09:28 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2023-01-19 11:09:28 AM - 		Name         : Visual Studio core editor
2023-01-19 11:09:28 AM - 		Version      : [16.0,17.0)
2023-01-19 11:09:28 AM - 
2023-01-19 11:09:28 AM - Signature Details...
2023-01-19 11:09:28 AM - 	Extension is not signed.
2023-01-19 11:09:28 AM - 
2023-01-19 11:09:28 AM - Searching for applicable products...
2023-01-19 11:09:28 AM - Found installed product - Global Location
2023-01-19 11:09:28 AM - Found installed product - Visual Studio Enterprise 2022 Preview
2023-01-19 11:09:28 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by codeputer** [comment]
Found the PR for a VS 2022 solution.  Moving to that version
